In [1]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt

In [2]:
%ls apartment_data/

ls: apartment_data/: No such file or directory

In [3]:
df = pd.read_csv("/Users/hajun/Desktop/대쉬보드 프로젝트/P-4 서울시 부동산 실거래가 정보/서울시 부동산 실거래가 정보.csv", encoding="cp949")

In [5]:
df.tail(10)

,접수연도,자치구명,법정동코드,법정동명,건물명,계약일,물건금액(만원),건물면적(㎡),토지면적(㎡),층,건축년도,건물용도,신고한 개업공인중개사 시군구명
1048565,2017,동작구,10200,상도동,NaN,20170304,25800,35.50,56.00,NaN,1983.0,단독다가구,NaN
1048566,2017,강서구,10400,가양동,강변,20170304,36800,49.50,0.00,7.0,1992.0,아파트,NaN
1048567,2017,성북구,13500,종암동,NaN,20170304,26000,45.53,76.00,NaN,1980.0,단독다가구,NaN
1048568,2017,동작구,10900,신대방동,동우맨션(360-80),20170304,23800,56.43,28.90,2.0,2002.0,연립다세대,NaN
1048569,2017,구로구,10300,가리봉동,NaN,20170304,31050,39.99,76.00,NaN,1973.0,단독다가구,NaN
1048570,2017,은평구,10500,구산동,갈현현대,20170304,35000,114.95,0.00,7.0,1998.0,아파트,NaN
1048571,2017,구로구,10800,오류동,프리가,20170304,9900,20.73,29.80,7.0,2013.0,오피스텔,NaN
1048572,2017,성북구,13900,석관동,두산,20170304,35000,59.97,0.00,2.0,1998.0,아파트,NaN
1048573,2017,은평구,10500,구산동,플러스빌(2-16),20170304,14800,26.67,11.26,7.0,2010.0,연립다세대,NaN
1048574,2017,강서구,10400,가양동,가양6단지,20170304,38800,49.50,0.00,13.0,1992.0,아파트,NaN